from PyQt5 import QtCore, QtGui, QtWidgets
import ui.resources.icon_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1031, 613)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("*{\n"
                                         "    border: none;\n"
                                         "    background-color: transparent;\n"
                                         "    color: #fff;\n"
                                         "}\n"
                                         "#centralwiget{\n"
                                         "    background-color: rgb(255, 255, 255);\n"
                                         "}\n"
                                         "#side_menu{\n"
                                         "background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, "
                                         "stop:0 rgba(9, 22, 41, 255), stop:1 rgba(9, 31, 63, 255));\n "
                                         "    border-radius: 20px;\n"
                                         "}\n"
                                         "#header{\n"
                                         "    background-color: rgb(5, 17, 34);\n"
                                         "}\n"
                                         "QPushButton{\n"
                                         "    padding: 10px;\n"
                                         "    background-color: rgb(5, 17, 34);\n"
                                         "    border-radius: 10px;\n"
                                         "    color: white;\n"
                                         "}\n"
                                         "QPushButton:hover{\n"
                                         "background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.130682, "
                                         "y2:0.165, stop:0 rgba(34, 120, 239, 255), stop:1 rgba(145, 185, 239, "
                                         "255));\n "
                                         "}\n"
                                         "#main_body{\n"
                                         "    background-color: white;\n"
                                         "    border-radius: 10px;\n"
                                         "}\n"
                                         "QScrollBar::handle:vertical\n"
                                         "{\n"
                                         "      background-color: rgb(232, 232, 232);\n"
                                         "      min-height: 5px;\n"
                                         "      border-radius: 6px;\n"
                                         "}\n"
                                         "QScrollBar::add-line:vertical \n"
                                         "{\n"
                                         "      border: none;\n"
                                         "      background: none;\n"
                                         "}\n"
                                         "\n"
                                         "QScrollBar::sub-line:vertical\n"
                                         "{\n"
                                         "      border: none;\n"
                                         "      background: none;\n"
                                         "}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 500))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 500))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.side_menu = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.side_menu.sizePolicy().hasHeightForWidth())
        self.side_menu.setSizePolicy(sizePolicy)
        self.side_menu.setMinimumSize(QtCore.QSize(200, 0))
        self.side_menu.setMaximumSize(QtCore.QSize(0, 16777215))
        self.side_menu.setObjectName("side_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.side_menu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.side_menu)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.home = QtWidgets.QPushButton(self.frame_5)
        self.home.setMinimumSize(QtCore.QSize(170, 0))
        self.home.setMaximumSize(QtCore.QSize(170, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.home.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home.setIcon(icon)
        self.home.setIconSize(QtCore.QSize(24, 24))
        self.home.setObjectName("home")
        self.verticalLayout_3.addWidget(self.home)
        self.wallet = QtWidgets.QPushButton(self.frame_5)
        self.wallet.setMinimumSize(QtCore.QSize(170, 53))
        self.wallet.setMaximumSize(QtCore.QSize(170, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.wallet.setFont(font)
        self.wallet.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/dollar-sign.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.wallet.setIcon(icon1)
        self.wallet.setIconSize(QtCore.QSize(24, 24))
        self.wallet.setObjectName("wallet")
        self.verticalLayout_3.addWidget(self.wallet)
        self.verticalLayout_2.addWidget(self.frame_5, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.frame = QtWidgets.QFrame(self.side_menu)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setMinimumSize(QtCore.QSize(170, 0))
        self.pushButton_5.setMaximumSize(QtCore.QSize(170, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton:hover{\n"
                                        "background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, "
                                        "stop:0 rgba(165, 4, 77, 255), stop:1 rgba(165, 117, 139, 255));\n "
                                        "}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon2)
        self.pushButton_5.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_5.addWidget(self.pushButton_5)
        self.verticalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.side_menu)
        self.main_body = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_body.sizePolicy().hasHeightForWidth())
        self.main_body.setSizePolicy(sizePolicy)
        self.main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.main_body)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_4 = QtWidgets.QFrame(self.main_body)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 53))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 53))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_16 = QtWidgets.QFrame(self.frame_7)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.search_bar = QtWidgets.QLineEdit(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_bar.sizePolicy().hasHeightForWidth())
        self.search_bar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.search_bar.setFont(font)
        self.search_bar.setStyleSheet("border: 1px solid rgb(232, 232, 232);\n"
                                      "border-radius: 15px;\n"
                                      "color: rgb(167, 167, 167);")
        self.search_bar.setObjectName("search_bar")
        self.horizontalLayout_4.addWidget(self.search_bar)
        self.search = QtWidgets.QPushButton(self.frame_16)
        self.search.setStyleSheet("QPushButton {\n"
                                  "    background-color: rgba(255, 255, 255, 0);\n"
                                  "}")
        self.search.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/search-hover.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/search-hover.svg"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/search-hover.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.search.setIcon(icon3)
        self.search.setIconSize(QtCore.QSize(24, 24))
        self.search.setCheckable(False)
        self.search.setObjectName("search")
        self.horizontalLayout_4.addWidget(self.search)
        self.horizontalLayout_5.addWidget(self.frame_16)
        self.verticalLayout_6.addWidget(self.frame_7)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.frame_6 = QtWidgets.QFrame(self.main_body)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_7.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_12 = QtWidgets.QFrame(self.frame_6)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 43))
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 43))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.verticalLayout_7.addWidget(self.frame_12)
        self.scrollArea = QtWidgets.QScrollArea(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 766, 777))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 777))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.product1 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.product1.setStyleSheet("border: 2px solid rgb(232, 232, 232);\n"
                                    "border-radius: 20px;")
        self.product1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.product1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.product1.setObjectName("product1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.product1)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_8 = QtWidgets.QFrame(self.product1)
        self.frame_8.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_8.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_8.setStyleSheet("border: 0px;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.picture1 = QtWidgets.QLabel(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picture1.sizePolicy().hasHeightForWidth())
        self.picture1.setSizePolicy(sizePolicy)
        self.picture1.setStyleSheet("border: 0px;")
        self.picture1.setText("")
        self.picture1.setPixmap(QtGui.QPixmap("F:\\pyqt\\ui\\ui\\../resources/products/rtx4090.png"))
        self.picture1.setObjectName("picture1")
        self.verticalLayout_16.addWidget(self.picture1)
        self.horizontalLayout_6.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.product1)
        self.frame_9.setStyleSheet("border: 0px;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_12.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.buy1text = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buy1text.setFont(font)
        self.buy1text.setStyleSheet("border: 0px;\n"
                                    "color: black;")
        self.buy1text.setObjectName("buy1text")
        self.horizontalLayout_12.addWidget(self.buy1text, 0, QtCore.Qt.AlignTop)
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: black;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_8.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.buy1 = QtWidgets.QPushButton(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buy1.sizePolicy().hasHeightForWidth())
        self.buy1.setSizePolicy(sizePolicy)
        self.buy1.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buy1.setFont(font)
        self.buy1.setStyleSheet("QPushButton {\n"
                                "    background-color: rgba(255, 255, 255, 0);\n"
                                "    color: black;\n"
                                "    border: 1px solid rgb(232, 232, 232);\n"
                                "    border-radius: 10px;\n"
                                "}\n"
                                "QPushButton:hover{\n"
                                "    background-color: rgb(232, 232, 232);\n"
                                "}")
        self.buy1.setObjectName("buy1")
        self.verticalLayout_8.addWidget(self.buy1, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignBottom)
        self.horizontalLayout_12.addWidget(self.frame_10, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_6.addWidget(self.frame_9)
        self.verticalLayout.addWidget(self.product1)
        self.product2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.product2.setStyleSheet("border: 2px solid rgb(232, 232, 232);\n"
                                    "border-radius: 20px;")
        self.product2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.product2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.product2.setObjectName("product2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.product2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_11 = QtWidgets.QFrame(self.product2)
        self.frame_11.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_11.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_11.setStyleSheet("border: 0px;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.picture1_2 = QtWidgets.QLabel(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picture1_2.sizePolicy().hasHeightForWidth())
        self.picture1_2.setSizePolicy(sizePolicy)
        self.picture1_2.setStyleSheet("border: 0px;")
        self.picture1_2.setText("")
        self.picture1_2.setPixmap(QtGui.QPixmap("F:\\pyqt\\ui\\ui\\../resources/products/i9_12900.png"))
        self.picture1_2.setObjectName("picture1_2")
        self.verticalLayout_17.addWidget(self.picture1_2)
        self.horizontalLayout_7.addWidget(self.frame_11)
        self.frame_13 = QtWidgets.QFrame(self.product2)
        self.frame_13.setStyleSheet("border: 0px;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_13.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.buy2text = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buy2text.setFont(font)
        self.buy2text.setStyleSheet("border: 0px;\n"
                                    "color: black;")
        self.buy2text.setObjectName("buy2text")
        self.horizontalLayout_13.addWidget(self.buy2text, 0, QtCore.Qt.AlignTop)
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label2 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label2.setFont(font)
        self.label2.setStyleSheet("color: black;")
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setObjectName("label2")
        self.verticalLayout_10.addWidget(self.label2, 0, QtCore.Qt.AlignHCenter)
        self.buy2 = QtWidgets.QPushButton(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buy2.sizePolicy().hasHeightForWidth())
        self.buy2.setSizePolicy(sizePolicy)
        self.buy2.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buy2.setFont(font)
        self.buy2.setStyleSheet("QPushButton {\n"
                                "    background-color: rgba(255, 255, 255, 0);\n"
                                "    color: black;\n"
                                "    border: 1px solid rgb(232, 232, 232);\n"
                                "    border-radius: 10px;\n"
                                "}\n"
                                "QPushButton:hover{\n"
                                "    background-color: rgb(232, 232, 232);\n"
                                "}")
        self.buy2.setObjectName("buy2")
        self.verticalLayout_10.addWidget(self.buy2, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignBottom)
        self.horizontalLayout_13.addWidget(self.frame_14, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_7.addWidget(self.frame_13)
        self.verticalLayout.addWidget(self.product2)
        self.product3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.product3.setStyleSheet("border: 2px solid rgb(232, 232, 232);\n"
                                    "border-radius: 20px;")
        self.product3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.product3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.product3.setObjectName("product3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.product3)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_15 = QtWidgets.QFrame(self.product3)
        self.frame_15.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_15.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_15.setStyleSheet("border: 0px;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.picture3 = QtWidgets.QLabel(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picture3.sizePolicy().hasHeightForWidth())
        self.picture3.setSizePolicy(sizePolicy)
        self.picture3.setStyleSheet("border: 0px;")
        self.picture3.setText("")
        self.picture3.setPixmap(QtGui.QPixmap("F:\\pyqt\\ui\\ui\\../resources/products/asus-z690-a.png"))
        self.picture3.setObjectName("picture3")
        self.verticalLayout_18.addWidget(self.picture3)
        self.horizontalLayout_8.addWidget(self.frame_15)
        self.frame_17 = QtWidgets.QFrame(self.product3)
        self.frame_17.setStyleSheet("border: 0px;")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_14.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.buy3text = QtWidgets.QLabel(self.frame_17)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buy3text.setFont(font)
        self.buy3text.setStyleSheet("border: 0px;\n"
                                    "color: black;")
        self.buy3text.setObjectName("buy3text")
        self.horizontalLayout_14.addWidget(self.buy3text, 0, QtCore.Qt.AlignTop)
        self.frame_18 = QtWidgets.QFrame(self.frame_17)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_12.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label3 = QtWidgets.QLabel(self.frame_18)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label3.setFont(font)
        self.label3.setStyleSheet("color: black;")
        self.label3.setAlignment(QtCore.Qt.AlignCenter)
        self.label3.setObjectName("label3")
        self.verticalLayout_12.addWidget(self.label3, 0, QtCore.Qt.AlignHCenter)
        self.buy3 = QtWidgets.QPushButton(self.frame_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buy3.sizePolicy().hasHeightForWidth())
        self.buy3.setSizePolicy(sizePolicy)
        self.buy3.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buy3.setFont(font)
        self.buy3.setStyleSheet("QPushButton {\n"
                                "    background-color: rgba(255, 255, 255, 0);\n"
                                "    color: black;\n"
                                "    border: 1px solid rgb(232, 232, 232);\n"
                                "    border-radius: 10px;\n"
                                "}\n"
                                "QPushButton:hover{\n"
                                "    background-color: rgb(232, 232, 232);\n"
                                "}")
        self.buy3.setObjectName("buy3")
        self.verticalLayout_12.addWidget(self.buy3, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignBottom)
        self.horizontalLayout_14.addWidget(self.frame_18, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_8.addWidget(self.frame_17)
        self.verticalLayout.addWidget(self.product3)
        self.product4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.product4.setStyleSheet("border: 2px solid rgb(232, 232, 232);\n"
                                    "border-radius: 20px;")
        self.product4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.product4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.product4.setObjectName("product4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.product4)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_19 = QtWidgets.QFrame(self.product4)
        self.frame_19.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_19.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_19.setStyleSheet("border: 0px;")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.picture4 = QtWidgets.QLabel(self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picture4.sizePolicy().hasHeightForWidth())
        self.picture4.setSizePolicy(sizePolicy)
        self.picture4.setStyleSheet("border: 0px;")
        self.picture4.setText("")
        self.picture4.setPixmap(QtGui.QPixmap("F:\\pyqt\\ui\\ui\\../resources/products/bequiet1000w.png"))
        self.picture4.setObjectName("picture4")
        self.verticalLayout_19.addWidget(self.picture4)
        self.horizontalLayout_9.addWidget(self.frame_19)
        self.frame_20 = QtWidgets.QFrame(self.product4)
        self.frame_20.setStyleSheet("border: 0px;")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_15.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.buy4text = QtWidgets.QLabel(self.frame_20)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buy4text.setFont(font)
        self.buy4text.setStyleSheet("border: 0px;\n"
                                    "color: black;")
        self.buy4text.setObjectName("buy4text")
        self.horizontalLayout_15.addWidget(self.buy4text, 0, QtCore.Qt.AlignTop)
        self.frame_21 = QtWidgets.QFrame(self.frame_20)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_13.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label4 = QtWidgets.QLabel(self.frame_21)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label4.setFont(font)
        self.label4.setStyleSheet("color: black;")
        self.label4.setAlignment(QtCore.Qt.AlignCenter)
        self.label4.setObjectName("label4")
        self.verticalLayout_13.addWidget(self.label4, 0, QtCore.Qt.AlignHCenter)
        self.buy4 = QtWidgets.QPushButton(self.frame_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buy4.sizePolicy().hasHeightForWidth())
        self.buy4.setSizePolicy(sizePolicy)
        self.buy4.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buy4.setFont(font)
        self.buy4.setStyleSheet("QPushButton {\n"
                                "    background-color: rgba(255, 255, 255, 0);\n"
                                "    color: black;\n"
                                "    border: 1px solid rgb(232, 232, 232);\n"
                                "    border-radius: 10px;\n"
                                "}\n"
                                "QPushButton:hover{\n"
                                "    background-color: rgb(232, 232, 232);\n"
                                "}")
        self.buy4.setObjectName("buy4")
        self.verticalLayout_13.addWidget(self.buy4, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignBottom)
        self.horizontalLayout_15.addWidget(self.frame_21, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_9.addWidget(self.frame_20)
        self.verticalLayout.addWidget(self.product4)
        self.product5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.product5.setStyleSheet("border: 2px solid rgb(232, 232, 232);\n"
                                    "border-radius: 20px;")
        self.product5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.product5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.product5.setObjectName("product5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.product5)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_25 = QtWidgets.QFrame(self.product5)
        self.frame_25.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_25.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_25.setStyleSheet("border: 0px;")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.picture5 = QtWidgets.QLabel(self.frame_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picture5.sizePolicy().hasHeightForWidth())
        self.picture5.setSizePolicy(sizePolicy)
        self.picture5.setStyleSheet("border: 0px;")
        self.picture5.setText("")
        self.picture5.setPixmap(QtGui.QPixmap("F:\\pyqt\\ui\\ui\\../resources/products/ssd2tb.png"))
        self.picture5.setObjectName("picture5")
        self.verticalLayout_21.addWidget(self.picture5)
        self.horizontalLayout_11.addWidget(self.frame_25)
        self.frame_26 = QtWidgets.QFrame(self.product5)
        self.frame_26.setStyleSheet("border: 0px;")
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_17.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.buy5text = QtWidgets.QLabel(self.frame_26)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buy5text.setFont(font)
        self.buy5text.setStyleSheet("border: 0px;\n"
                                    "color: black;")
        self.buy5text.setObjectName("buy5text")
        self.horizontalLayout_17.addWidget(self.buy5text, 0, QtCore.Qt.AlignTop)
        self.frame_27 = QtWidgets.QFrame(self.frame_26)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_15.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label5 = QtWidgets.QLabel(self.frame_27)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label5.setFont(font)
        self.label5.setStyleSheet("color: black;")
        self.label5.setAlignment(QtCore.Qt.AlignCenter)
        self.label5.setObjectName("label5")
        self.verticalLayout_15.addWidget(self.label5, 0, QtCore.Qt.AlignHCenter)
        self.buy5 = QtWidgets.QPushButton(self.frame_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buy5.sizePolicy().hasHeightForWidth())
        self.buy5.setSizePolicy(sizePolicy)
        self.buy5.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buy5.setFont(font)
        self.buy5.setStyleSheet("QPushButton {\n"
                                "    background-color: rgba(255, 255, 255, 0);\n"
                                "    color: black;\n"
                                "    border: 1px solid rgb(232, 232, 232);\n"
                                "    border-radius: 10px;\n"
                                "}\n"
                                "QPushButton:hover{\n"
                                "    background-color: rgb(232, 232, 232);\n"
                                "}")
        self.buy5.setObjectName("buy5")
        self.verticalLayout_15.addWidget(self.buy5, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignBottom)
        self.horizontalLayout_17.addWidget(self.frame_27, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_11.addWidget(self.frame_26)
        self.verticalLayout.addWidget(self.product5)
        self.product6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.product6.setStyleSheet("border: 2px solid rgb(232, 232, 232);\n"
                                    "border-radius: 20px;")
        self.product6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.product6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.product6.setObjectName("product6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.product6)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_22 = QtWidgets.QFrame(self.product6)
        self.frame_22.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_22.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_22.setStyleSheet("border: 0px;")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.picture6 = QtWidgets.QLabel(self.frame_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picture6.sizePolicy().hasHeightForWidth())
        self.picture6.setSizePolicy(sizePolicy)
        self.picture6.setStyleSheet("border: 0px;")
        self.picture6.setText("")
        self.picture6.setPixmap(QtGui.QPixmap("F:\\pyqt\\ui\\ui\\../resources/products/ddr5-6200.png"))
        self.picture6.setObjectName("picture6")
        self.verticalLayout_20.addWidget(self.picture6)
        self.horizontalLayout_10.addWidget(self.frame_22)
        self.frame_23 = QtWidgets.QFrame(self.product6)
        self.frame_23.setStyleSheet("border: 0px;")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_16.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.buy6text = QtWidgets.QLabel(self.frame_23)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buy6text.setFont(font)
        self.buy6text.setStyleSheet("border: 0px;\n"
                                    "color: black;")
        self.buy6text.setObjectName("buy6text")
        self.horizontalLayout_16.addWidget(self.buy6text, 0, QtCore.Qt.AlignTop)
        self.frame_24 = QtWidgets.QFrame(self.frame_23)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_14.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label6 = QtWidgets.QLabel(self.frame_24)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label6.setFont(font)
        self.label6.setStyleSheet("color: black;")
        self.label6.setAlignment(QtCore.Qt.AlignCenter)
        self.label6.setObjectName("label6")
        self.verticalLayout_14.addWidget(self.label6, 0, QtCore.Qt.AlignHCenter)
        self.buy6 = QtWidgets.QPushButton(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buy6.sizePolicy().hasHeightForWidth())
        self.buy6.setSizePolicy(sizePolicy)
        self.buy6.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buy6.setFont(font)
        self.buy6.setStyleSheet("QPushButton {\n"
                                "    background-color: rgba(255, 255, 255, 0);\n"
                                "    color: black;\n"
                                "    border: 1px solid rgb(232, 232, 232);\n"
                                "    border-radius: 10px;\n"
                                "}\n"
                                "QPushButton:hover{\n"
                                "    background-color: rgb(232, 232, 232);\n"
                                "}")
        self.buy6.setObjectName("buy6")
        self.verticalLayout_14.addWidget(self.buy6, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignBottom)
        self.horizontalLayout_16.addWidget(self.frame_24, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_10.addWidget(self.frame_23)
        self.verticalLayout.addWidget(self.product6)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.scrollArea)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.horizontalLayout.addWidget(self.main_body)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.header = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        self.header.setMinimumSize(QtCore.QSize(0, 0))
        self.header.setMaximumSize(QtCore.QSize(16777215, 100))
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.side_menu_toggle = QtWidgets.QFrame(self.header)
        self.side_menu_toggle.setMinimumSize(QtCore.QSize(100, 0))
        self.side_menu_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.side_menu_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_menu_toggle.setObjectName("side_menu_toggle")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.side_menu_toggle)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.side_menu_toggle)
        self.pushButton.setMinimumSize(QtCore.QSize(170, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(170, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: white;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/align-justify.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/align-justify.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton.setIcon(icon4)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setCheckable(False)
        self.pushButton.setChecked(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.horizontalLayout_2.addWidget(self.side_menu_toggle, 0, QtCore.Qt.AlignLeft)
        self.frame_3 = QtWidgets.QFrame(self.header)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.logged_as = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.logged_as.setFont(font)
        self.logged_as.setText("")
        self.logged_as.setAlignment(QtCore.Qt.AlignCenter)
        self.logged_as.setObjectName("logged_as")
        self.horizontalLayout_18.addWidget(self.logged_as)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.gridLayout.addWidget(self.header, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.home.setText(_translate("MainWindow", "HOME"))
        self.wallet.setText(_translate("MainWindow", "WALLET"))
        self.pushButton_5.setText(_translate("MainWindow", "LOGOUT"))
        self.label_3.setText(_translate("MainWindow", "Popular"))
        self.buy1text.setText(_translate("MainWindow", "Videocard PALIT GeForce RTX 4090 GAMERACK 24G"))
        self.label.setText(_translate("MainWindow", "2299$"))
        self.buy1.setText(_translate("MainWindow", "Buy"))
        self.buy2text.setText(_translate("MainWindow", "Proccessor Intel Core i9-12900K LGA1700 16 x 3200 Mhz "))
        self.label2.setText(_translate("MainWindow", "599$"))
        self.buy2.setText(_translate("MainWindow", "Buy"))
        self.buy3text.setText(_translate("MainWindow", "Motherboard ASUS PRIME Z690-A"))
        self.label3.setText(_translate("MainWindow", "399$"))
        self.buy3.setText(_translate("MainWindow", "Buy"))
        self.buy4text.setText(_translate("MainWindow", "Power supply be quiet! Straight power 1000W"))
        self.label4.setText(_translate("MainWindow", "249$"))
        self.buy4.setText(_translate("MainWindow", "Buy"))
        self.buy5text.setText(_translate("MainWindow", "SSD Samsung 980 PRO 2TB MZ-V8P2T0BW"))
        self.label5.setText(_translate("MainWindow", "299$"))
        self.buy5.setText(_translate("MainWindow", "Buy"))
        self.buy6text.setText(_translate("MainWindow", "RAM Corsair Dominator Platinum 32GB DDR5 6200Mhz"))
        self.label6.setText(_translate("MainWindow", "559$"))
        self.buy6.setText(_translate("MainWindow", "Buy"))
        self.pushButton.setText(_translate("MainWindow", "MENU"))
