# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\pyqt\ui\ui\buying.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Buying(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(791, 463)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.cart_page = QtWidgets.QWidget()
        self.cart_page.setObjectName("cart_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.cart_page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.cart_page)
        self.frame.setStyleSheet("*{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"}\n"
"#centralwiget{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"#side_menu{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(9, 22, 41, 255), stop:1 rgba(9, 31, 63, 255));\n"
"    border-radius: 20px;\n"
"}\n"
"#header{\n"
"    background-color: rgb(5, 17, 34);\n"
"}\n"
"QPushButton{\n"
"    padding: 10px;\n"
"    background-color: rgb(5, 17, 34);\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.130682, y2:0.165, stop:0 rgba(34, 120, 239, 255), stop:1 rgba(145, 185, 239, 255));\n"
"}\n"
"#main_body{\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"QScrollBar::handle:vertical\n"
"{\n"
"      background-color: rgb(232, 232, 232);\n"
"      min-height: 5px;\n"
"      border-radius: 6px;\n"
"}\n"
"QScrollBar::add-line:vertical \n"
"{\n"
"      border: none;\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"      border: none;\n"
"      background: none;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("background-color: white;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_3.setStyleSheet("QFrame{\n"
"    border: 2px solid rgb(232, 232, 232);\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: black;\n"
"border: transparent;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_13 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.product_name = QtWidgets.QLabel(self.frame_13)
        self.product_name.setGeometry(QtCore.QRect(9, 9, 641, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.product_name.sizePolicy().hasHeightForWidth())
        self.product_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.product_name.setFont(font)
        self.product_name.setStyleSheet("color: black;")
        self.product_name.setObjectName("product_name")
        self.total_sum = QtWidgets.QLabel(self.frame_13)
        self.total_sum.setGeometry(QtCore.QRect(10, 250, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.total_sum.setFont(font)
        self.total_sum.setStyleSheet("color: black;")
        self.total_sum.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.total_sum.setObjectName("total_sum")
        self.horizontalLayout_6.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.frame_4)
        self.frame_14.setMinimumSize(QtCore.QSize(94, 0))
        self.frame_14.setMaximumSize(QtCore.QSize(94, 16777215))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.product_amount = QtWidgets.QSpinBox(self.frame_14)
        self.product_amount.setGeometry(QtCore.QRect(0, 30, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.product_amount.setFont(font)
        self.product_amount.setStyleSheet("QSpinBox {\n"
"    border: 2px solid black;\n"
"    border-radius: 7px;\n"
"    background-color: transparent;\n"
"    color: black;\n"
"}\n"
"QSpinBox::up-arrow { \n"
"    border-left: 5px solid none;\n"
"    border-right: 5px solid none; \n"
"    border-bottom: 5px solid black; \n"
"    width: 0px; \n"
"    height: 0px; \n"
"}\n"
"QSpinBox::up-button {\n"
"    background-color: transparent; \n"
"}\n"
"QSpinBox::down-arrow {\n"
"    border-left: 5px solid none;\n"
"    border-right: 5px solid none; \n"
"    border-top: 5px solid black; \n"
"    width: 0px; \n"
"    height: 0px; \n"
"}\n"
"QSpinBox::down-button { \n"
"    background-color: transparent; \n"
"}\n"
"")
        self.product_amount.setObjectName("product_amount")
        self.horizontalLayout_6.addWidget(self.frame_14, 0, QtCore.Qt.AlignRight)
        self.gridLayout.addWidget(self.frame_4, 1, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.back = QtWidgets.QPushButton(self.frame_5)
        self.back.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.back.setFont(font)
        self.back.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: black;\n"
"    border: 2px solid rgb(232, 232, 232);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(232, 232, 232);\n"
"}")
        self.back.setObjectName("back")
        self.horizontalLayout.addWidget(self.back, 0, QtCore.Qt.AlignLeft)
        self.proceed = QtWidgets.QPushButton(self.frame_5)
        self.proceed.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.proceed.setFont(font)
        self.proceed.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: black;\n"
"    border: 2px solid rgb(232, 232, 232);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(232, 232, 232);\n"
"}")
        self.proceed.setObjectName("proceed")
        self.horizontalLayout.addWidget(self.proceed, 0, QtCore.Qt.AlignRight)
        self.gridLayout.addWidget(self.frame_5, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout_3.addWidget(self.frame)
        self.stackedWidget.addWidget(self.cart_page)
        self.confirmation_page = QtWidgets.QWidget()
        self.confirmation_page.setObjectName("confirmation_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.confirmation_page)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_6 = QtWidgets.QFrame(self.confirmation_page)
        self.frame_6.setStyleSheet("*{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"}\n"
"#centralwiget{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"#side_menu{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(9, 22, 41, 255), stop:1 rgba(9, 31, 63, 255));\n"
"    border-radius: 20px;\n"
"}\n"
"#header{\n"
"    background-color: rgb(5, 17, 34);\n"
"}\n"
"QPushButton{\n"
"    padding: 10px;\n"
"    background-color: rgb(5, 17, 34);\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.130682, y2:0.165, stop:0 rgba(34, 120, 239, 255), stop:1 rgba(145, 185, 239, 255));\n"
"}\n"
"#main_body{\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"QScrollBar::handle:vertical\n"
"{\n"
"      background-color: rgb(232, 232, 232);\n"
"      min-height: 5px;\n"
"      border-radius: 6px;\n"
"}\n"
"QScrollBar::add-line:vertical \n"
"{\n"
"      border: none;\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"      border: none;\n"
"      background: none;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setStyleSheet("background-color: white;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_3.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cancel_2 = QtWidgets.QPushButton(self.frame_8)
        self.cancel_2.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cancel_2.setFont(font)
        self.cancel_2.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: black;\n"
"    border: 2px solid rgb(232, 232, 232);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(232, 232, 232);\n"
"}")
        self.cancel_2.setObjectName("cancel_2")
        self.horizontalLayout_3.addWidget(self.cancel_2, 0, QtCore.Qt.AlignLeft)
        self.proceed_2 = QtWidgets.QPushButton(self.frame_8)
        self.proceed_2.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.proceed_2.setFont(font)
        self.proceed_2.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: black;\n"
"    border: 2px solid rgb(232, 232, 232);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(232, 232, 232);\n"
"}")
        self.proceed_2.setObjectName("proceed_2")
        self.horizontalLayout_3.addWidget(self.proceed_2, 0, QtCore.Qt.AlignRight)
        self.gridLayout_2.addWidget(self.frame_8, 2, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_9.setStyleSheet("QFrame{\n"
"    border: 2px solid rgb(232, 232, 232);\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: black;\n"
"border: transparent;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.gridLayout_2.addWidget(self.frame_9, 0, 0, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.frame_7)
        self.frame_10.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_4 = QtWidgets.QLabel(self.frame_10)
        self.label_4.setGeometry(QtCore.QRect(330, 0, 289, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 50))
        self.label_4.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: black;")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.frame_10)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 300, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(0, 50))
        self.label_6.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: black;")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_10)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 289, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 50))
        self.label_7.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: black;")
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_10)
        self.label_8.setGeometry(QtCore.QRect(10, 250, 289, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 50))
        self.label_8.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: black;")
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.balance = QtWidgets.QLabel(self.frame_10)
        self.balance.setGeometry(QtCore.QRect(550, 40, 191, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.balance.sizePolicy().hasHeightForWidth())
        self.balance.setSizePolicy(sizePolicy)
        self.balance.setMinimumSize(QtCore.QSize(0, 50))
        self.balance.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.balance.setFont(font)
        self.balance.setStyleSheet("color: black;")
        self.balance.setText("")
        self.balance.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.balance.setObjectName("balance")
        self.cart = QtWidgets.QLabel(self.frame_10)
        self.cart.setGeometry(QtCore.QRect(550, 80, 191, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cart.sizePolicy().hasHeightForWidth())
        self.cart.setSizePolicy(sizePolicy)
        self.cart.setMinimumSize(QtCore.QSize(0, 50))
        self.cart.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cart.setFont(font)
        self.cart.setStyleSheet("color: black;")
        self.cart.setText("")
        self.cart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cart.setObjectName("cart")
        self.remain = QtWidgets.QLabel(self.frame_10)
        self.remain.setGeometry(QtCore.QRect(550, 250, 191, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remain.sizePolicy().hasHeightForWidth())
        self.remain.setSizePolicy(sizePolicy)
        self.remain.setMinimumSize(QtCore.QSize(0, 50))
        self.remain.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.remain.setFont(font)
        self.remain.setStyleSheet("color: black;")
        self.remain.setText("")
        self.remain.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.remain.setObjectName("remain")
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setGeometry(QtCore.QRect(10, 240, 731, 3))
        self.frame_11.setMinimumSize(QtCore.QSize(0, 3))
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 3))
        self.frame_11.setStyleSheet("border: 3px solid black;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.not_enough = QtWidgets.QLabel(self.frame_10)
        self.not_enough.setGeometry(QtCore.QRect(220, 190, 300, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.not_enough.sizePolicy().hasHeightForWidth())
        self.not_enough.setSizePolicy(sizePolicy)
        self.not_enough.setMinimumSize(QtCore.QSize(0, 50))
        self.not_enough.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.not_enough.setFont(font)
        self.not_enough.setStyleSheet("color: red;")
        self.not_enough.setText("")
        self.not_enough.setAlignment(QtCore.Qt.AlignCenter)
        self.not_enough.setObjectName("not_enough")
        self.gridLayout_2.addWidget(self.frame_10, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_7)
        self.verticalLayout_6.addWidget(self.frame_6)
        self.stackedWidget.addWidget(self.confirmation_page)
        self.verticalLayout_5.addWidget(self.stackedWidget)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "CART"))
        self.product_name.setText(_translate("Dialog", "GEFORCE RTX 4090 GAMINGRACK RGB"))
        self.total_sum.setText(_translate("Dialog", "TOTAL: "))
        self.back.setText(_translate("Dialog", "CANCEL"))
        self.proceed.setText(_translate("Dialog", "PROCEED"))
        self.cancel_2.setText(_translate("Dialog", "CANCEL"))
        self.proceed_2.setText(_translate("Dialog", "PROCEED"))
        self.label_3.setText(_translate("Dialog", "CART"))
        self.label_4.setText(_translate("Dialog", "PAYMENT:"))
        self.label_6.setText(_translate("Dialog", "BALANCE:"))
        self.label_7.setText(_translate("Dialog", "CART:"))
        self.label_8.setText(_translate("Dialog", "REMAINING BALANCE:"))
