# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\pyqt\ui\ui\payment.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Payment(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(791, 463)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("*{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"}\n"
"#centralwiget{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"#side_menu{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(9, 22, 41, 255), stop:1 rgba(9, 31, 63, 255));\n"
"    border-radius: 20px;\n"
"}\n"
"#header{\n"
"    background-color: rgb(5, 17, 34);\n"
"}\n"
"QPushButton{\n"
"    padding: 10px;\n"
"    background-color: rgb(5, 17, 34);\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.130682, y2:0.165, stop:0 rgba(34, 120, 239, 255), stop:1 rgba(145, 185, 239, 255));\n"
"}\n"
"#main_body{\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"QScrollBar::handle:vertical\n"
"{\n"
"      background-color: rgb(232, 232, 232);\n"
"      min-height: 5px;\n"
"      border-radius: 6px;\n"
"}\n"
"QScrollBar::add-line:vertical \n"
"{\n"
"      border: none;\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"      border: none;\n"
"      background: none;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("background-color: white;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: black;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setGeometry(QtCore.QRect(100, 20, 562, 290))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("F:\\pyqt\\ui\\ui\\../resources/pay_form.png"))
        self.label.setObjectName("label")
        self.card_number = QtWidgets.QLineEdit(self.frame_4)
        self.card_number.setGeometry(QtCore.QRect(140, 60, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.card_number.setFont(font)
        self.card_number.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: black;")
        self.card_number.setObjectName("card_number")
        self.month = QtWidgets.QLineEdit(self.frame_4)
        self.month.setGeometry(QtCore.QRect(140, 140, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.month.setFont(font)
        self.month.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: black;")
        self.month.setObjectName("month")
        self.cardholder = QtWidgets.QLineEdit(self.frame_4)
        self.cardholder.setGeometry(QtCore.QRect(140, 220, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cardholder.setFont(font)
        self.cardholder.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: black;")
        self.cardholder.setObjectName("cardholder")
        self.year = QtWidgets.QLineEdit(self.frame_4)
        self.year.setGeometry(QtCore.QRect(280, 140, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.year.setFont(font)
        self.year.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: black;")
        self.year.setObjectName("year")
        self.cvv = QtWidgets.QLineEdit(self.frame_4)
        self.cvv.setGeometry(QtCore.QRect(560, 180, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cvv.setFont(font)
        self.cvv.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: black;")
        self.cvv.setObjectName("cvv")
        self.gridLayout.addWidget(self.frame_4, 1, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancel = QtWidgets.QPushButton(self.frame_5)
        self.cancel.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cancel.setFont(font)
        self.cancel.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: black;\n"
"    border: 2px solid rgb(232, 232, 232);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(232, 232, 232);\n"
"}")
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel, 0, QtCore.Qt.AlignLeft)
        self.proceed = QtWidgets.QPushButton(self.frame_5)
        self.proceed.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.proceed.setFont(font)
        self.proceed.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: black;\n"
"    border: 2px solid rgb(232, 232, 232);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(232, 232, 232);\n"
"}")
        self.proceed.setObjectName("proceed")
        self.horizontalLayout.addWidget(self.proceed, 0, QtCore.Qt.AlignRight)
        self.gridLayout.addWidget(self.frame_5, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "PAYMENT PAGE"))
        self.cancel.setText(_translate("Dialog", "BACK"))
        self.proceed.setText(_translate("Dialog", "OK"))
